#          Image Conversion into Arrays(NumPy)


#### Pillow version check...

In [22]:
import PIL

In [23]:
print('Installed Pillow Version:', PIL.__version__)

Installed Pillow Version: 8.2.0


### Properties of the image

In [24]:
from PIL import Image

In [25]:
image = Image.open('1.jpg')

In [26]:
print(image.format)
print(image.size)
print(image.mode)

JPEG
(2560, 1600)
RGB


### Converting an image into NumPy Array

In [27]:
from PIL import Image 

In [30]:
from numpy import asarray

In [31]:
img=Image.open('1.jpg')

In [32]:
numpydata=asarray(img)

In [33]:
print(type(numpydata))

<class 'numpy.ndarray'>


In [34]:
print(numpydata.shape)

(1600, 2560, 3)


### The value of each pixel of the NumPy array image

In [35]:
from PIL import Image


In [36]:
from numpy import asarray

In [38]:
img=Image.open('1.jpg')


In [39]:
numpydata=asarray(img)


In [40]:
print(numpydata)

[[[16  0  0]
  [17  0  0]
  [20  0  1]
  ...
  [ 4  8 17]
  [13 17 26]
  [20 24 33]]

 [[16  0  0]
  [17  0  0]
  [20  0  1]
  ...
  [ 3  7 16]
  [10 14 23]
  [16 20 29]]

 [[17  0  0]
  [18  0  0]
  [21  1  2]
  ...
  [ 1  5 14]
  [ 6 10 19]
  [ 9 13 22]]

 ...

 [[22  0  3]
  [22  0  3]
  [26  1  5]
  ...
  [ 0  4  7]
  [ 0  3  6]
  [ 0  3  6]]

 [[23  1  4]
  [23  0  2]
  [23  0  2]
  ...
  [ 0  4  7]
  [ 1  5  8]
  [ 1  5  8]]

 [[26  1  5]
  [23  0  2]
  [22  0  0]
  ...
  [ 1  5  8]
  [ 1  5  8]
  [ 2  6  9]]]
